{{- define "lugo.postgres-secrets" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secrets
type: Opaque
data:
  username: {{ .Values.global.database.username | b64enc }} 
  password: {{ .Values.global.database.password | b64enc }} 
  {{- if .Values.service.database -}}
  {{- range .Values.service.database -}}
  {{ .name }}: {{ printf "User ID=%s;Password=%s;Host=%s;Port=%s;Database=%s;" .Values.global.database.username .Values.global.database.password .Values.global.database.port .database | b64enc | quote }} 
  {{- end }}
  {{- end }}
{{- end }}


{{- define "lugo.tls-secrets" }}
{{- $cert := required "A valid .Values.global.tls.cert entry required" .Values.global.tls.cert -}}
{{- $key := required "A valid .Values.global.tls.key entry required" .Values.global.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-secrets
  namespace: default
data:
  tls.crt: {{ $cert | b64enc }}
  tls.key: {{ $key | b64enc }}
type: kubernetes.io/tls
{{- end }}