
{{- define "lugo.postgres-secrets"}}
{{- required "A valid .Values.global.database entry required" .Values.global.database }}
{{- with .Values.global.database }}
{{- $username := .username -}}
{{- $password := .password -}}
{{- $port := (( .port | toString )) -}}
{{- $host := .host -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secrets
type: Opaque
data:
  username: {{ $username | b64enc }} 
  password: {{ $password | b64enc }} 
  connectionString: {{ printf "User ID=%s;Password=%s;Host=%s;Port=%s;Database=%s;" $username $password $port .Values.service.name | b64enc | quote }} 
{{- end }}


{{- define "lugo.tls-secrets" }}
{{- required "A valid .Values.global.tls entry required" .Values.global.tls}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-secrets
  namespace: default
data:
  tls.crt: {{ .Values.global.tls.cert | b64enc}}
  tls.key: {{ .Values.global.tls.key | b64enc }}
type: kubernetes.io/tls
{{- end }}