{{- define "lugo.postgres-secrets" }}
{{- $username := .Values.global.database.username | toString }}
{{- $password := .Values.global.database.password | toString }}
{{- $port := .Values.global.database.port | toString }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secrets
type: Opaque
data:
  username: {{ $username | b64enc }} 
  password: {{ $password | b64enc }} 
  {{- if .Values.service.database }}
  {{- range .Values.service.database }}
  {{- $databaseName := .databaseName | toString }}
  {{ .name }}: {{ printf "User ID=%s;Password=%s;Host=%s;Port=%s;Database=%s;" $username $password $port $databaseName | b64enc | quote }} 
  {{- end }}
  {{- end }}
{{- end }}


{{- define "lugo.tls-secrets" }}
{{- $cert := required "A valid .Values.global.tls.cert entry required" .Values.global.tls.cert -}}
{{- $key := required "A valid .Values.global.tls.key entry required" .Values.global.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-secrets
  namespace: default
data:
  tls.crt: {{ $cert | b64enc }}
  tls.key: {{ $key | b64enc }}
type: kubernetes.io/tls
{{- end }}