{{- define "lugo.service-common" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service 
  labels:
    run: {{ .Release.Name }}-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Release.Name }}
{{- end }}