{{- $secret := lookup "v1" "Secret" {{ .Release.Namespace | quote }} "postgres-secret" -}}
{{- if $secret -}}
{{- else -}}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  username: {{ .Values.database.username | b64enc }} 
  password: {{ .Values.database.password | b64enc }} 
{{- end -}}