{{ required "A valid .Values.global.database entry is required" .Values.global.database }}
{{ if .Values.global.database.external}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-service
  labels:
    run: {{ .Release.Name }}-postgres-service
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.global.database.port }}
    targetPort: 5432
  selector:
    app: {{ .Release.Name }}-postgres

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}-postgres
  name: {{ .Release.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
        - image: {{ .Values.global.database.image}}
          name: {{ .Release.Name }}-postgres
          resources: {}
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-postgres-secrets
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-postgres-secrets
                key: password
      imagePullSecrets:
        - name: regcred
status: {}

{{- end }}