{{- required "A valid .Values.global.database entry required" .Values.global.database }}
{{- with .Values.global.database }}
{{- $username := .username }}
{{- $password := .password }}
{{- $port := (( .port | toString )) }}
{{- end }}
{{- $databaseName := .Release.Name }}
{{- $host := printf "%s-postgres-service" .Release.Name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secrets
type: Opaque
data:
  username: {{ .Values.global.database.username | b64enc }} 
  password: {{ .Values.global.database.password | b64enc }} 
  connectionString: {{ printf "User ID=%s;Password=%s;Host=%s-postgres-service;Port=%s;Database=%s;" $username $password $host $port $databaseName | b64enc | quote }} 