{{- $secret := lookup "v1" "Secret" "Default" "tls-secrets" -}}
{{- if $secret -}}
{{- else -}}
apiVersion: v1
kind: Secret
metadata:
  name: tls-secrets
  namespace: default
data:
  tls.crt: {{ .Values.tls.cert | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
type: kubernetes.io/tls
{{- end -}}