service:
  name: quantity
  image: quantity-api:latest
  repositoryName: quantity-api
  port: 80
  targetPort: 80
  replicaCount: 1
  environmentVariables:
    PORT: 80
    DEBUG: "*"
    NODE_ENV: "development"
    DB_DATABASE: "quantity"

global:
  database:
    host: host.minikube.interal
    username: root
    password: root
    port: 5432

  tls:
    cert: |
      aslkdfjalösdkf

    key: |
      alösjdföalskdf