service:
  name: transport
  image: transportreservationapi:latest
  pullPolicy: Never
  port: 80
  targetPort: 80
  replicas: 1

  environmentVariables:
    ASPNETCORE_ENVIRONMENT: Development

  database:
    - name: DefaultConnection
      databaseName: transport

global:
  database:
    host: host.minikube.internal
    username: root
    password: root
    port: 5432