apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    run: postgres-service
spec:
  ports:
  - protocol: TCP
    port: 5432 
    targetPort: 5432
  selector:
    app: postgres

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres 
          name: postgres
          resources: {}
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: password
      imagePullSecrets:
        - name: regcred
status: {}