apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  username: {{ .Values.global.database.username | b64enc }} 
  password: {{ .Values.global.database.password | b64enc }} 