service:
  name: phs_main
  image: phs_main:latest
  repositoryName: phs_main
  port: 80
  targetPort: 80
  replicas: 1
  environmentVariables:
    ASPNETCORE_ENVIRONMENT: Development
  database:
  - name: DefaultConnection
    databaseName: lundqvist_phsm1

global:
  github:
    username: USERNAME 
    access_token: TOKEN 

  database:
    host: host.minikube.internal
    username: root
    password: root
    port: 5432