apiVersion: v1
kind: Secret
metadata:
  name: tls-secrets
  namespace: default
data:
  tls.crt: {{ .Files.Get .Values.tls.certPath | b64enc }}
  tls.key: {{ .Files.Get .Values.tls.keyPath| b64enc }}
type: kubernetes.io/tls