{{- define "lugo.deployment-dotnet" }}
{{- $releaseName :=  default .Release.Name .Values.releaseNameOverride }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $releaseName }}
  name: {{ $releaseName }}
spec:
  replicas: {{ .Values.service.replicas }}
  selector:
    matchLabels:
      app: {{ $releaseName }}
  template:
    metadata:
      labels:
        app: {{ $releaseName }}
    spec:
      containers:
      - name: {{ $releaseName }}
        image: {{ .Values.service.image }}
        imagePullPolicy: {{ .Values.service.pullPolicy }}
        env:
        {{- range $key, $value := .Values.service.environmentVariables }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if .Values.service.database }}
        {{- range .Values.service.database }}
        {{- $stringName := print "ConnectionStrings__" .name }}
        - name: {{ $stringName }}
          valueFrom:
            secretKeyRef:
              name: {{ $releaseName }}-postgres-secrets
              key: {{ .name }}
        {{- end }}
        {{- end }}
        resources: {}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
{{- end }}

{{- define "lugo.deployment-node" }}
{{- $releaseName := .Values.service.nameOverride | default .Release.Name | quote  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $releaseName }}
  name: {{ $releaseName }}
spec:
  replicas: {{ .Values.service.replicas }}
  selector:
    matchLabels:
      app: {{ $releaseName }}
  template:
    metadata:
      labels:
        app: {{ $releaseName }}
    spec:
      containers:
      - name: {{ $releaseName }}
        image: {{ .Values.service.image }}
        env:
        {{- range $key, $value := .Values.service.environmentVariables }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: DB_HOST 
          value: {{ .Values.global.database.host }} 
        - name: DB_PORT
          value: {{ .Values.global.database.port | quote }} 
        - name: DB_NAME
          value: {{ .Values.service.name | quote }} 
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $releaseName }}-postgres-secrets
              key: password
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ $releaseName }}-postgres-secrets
              key: username 
        resources: {}
        ports:
          - containerPort: {{ .Values.service.targetPort }}
{{- end }}
