{{- define "lugo.ingress-https" }}
{{- $releaseName :=  default .Release.Name .Values.releaseNameOverride }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: {{ $releaseName }}-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class:  nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
spec:
  tls:
  - hosts:
    - {{ .Values.service.ingress.host }}  
    secretName: {{ $releaseName }}-tls-secrets
  rules:
  - host: {{ .Values.service.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $releaseName }}-service
            port: 
              number: {{ .Values.service.port }}
{{- end }}
