{{- define "lugo.service-common" }}
{{- $releaseName :=  default .Release.Name .Values.releaseNameOverride }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-service 
  labels:
    run: {{ $releaseName }}-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ $releaseName }}
{{- end }}