service:
  name: identity
  image: 879032840002.dkr.ecr.eu-north-1.amazonaws.com/lugoidentity:latest-dev
  pullPolicy: Never
  port: 80
  targetPort: 80
  replicas: 1

  environmentVariables:
    IDENTITY_PUBLIC_URL: http://identity.lugo.local
    ASPNETCORE_ENVIRONMENT: Development
    IdentityBaseAddress: http://identity-service
    IdentityRedirectUri: https://lugo.local

  ingress:
    host: identity.lugo.local  

  database:
  - name: DefaultConnection
    databaseName: Identity

global:
  database:
    host: postgres-service 
    username: root 
    password: root 
    port: 5432

  tls:
    cert: |
      test

    key: |
      test