service:
  name: capacity
  image: capacity:latest
  repositoryName: LogicAPI
  port: 80
  targetPort: 80
  replicas: 1
  environmentVariables:
    ASPNETCORE_ENVIRONMENT: Development
  database:
    - name: CapacityConnection
      databaseName: lugo_Capacity

global:
  github:
    username: USERNAME 
    access_token: TOKEN 

  database:
    host: host.minikube.internal
    username: root
    password: root
    port: 5432

  tls:
    cert: |
      xxx

    key: |
      xxx