apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secrets
type: Opaque
data:
  username: {{ .Values.global.database.username | b64enc }} 
  password: {{ .Values.global.database.password | b64enc }} 
  connectionString: {{ printf "User ID=%s;Password=%s;Host=%s;Port=%s;Database=%s;" .Values.global.database.username .Values.global.database.password .Values.global.database.host (( .Values.global.database.port | toString )) .Values.service.name | b64enc | quote }} 