apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-secrets
  namespace: default
data:
  tls.crt: {{ .Values.global.tls.cert | b64enc}}
  tls.key: {{ .Values.global.tls.key | b64enc }}
type: kubernetes.io/tls